Repository kopach/karma-sabarivka-reporter, pull requests merged in 2019-11, with the labels that each got.

#3 Update build.yaml
  .github/workflows/build.yaml
Labels: enhancement

#2 Update README.md
  README.md
Labels: documentation, enhancement

#1 Update README.md
  README.md
Labels: documentation, enhancement, good first issue
